# Generated by Django 4.2.3 on 2023-07-26 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_event_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='project_participant',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
